### PR TITLE
Update from study-template

### PR DESCRIPTION
**Pull request by benjimelito**
Update `.gitignore` from template. 
From `study-template`, refresh for cohort lm01

### CODE REVIEW

**Comment by BenGitsCode** [comment]
Do you have time to make a solution branch? If not, please open an issue that a solution branch should be created.

**Review by BenGitsCode — APPROVED** [review]
I'll merge this but please address my comment i.e. PR or issue.

**Comment by benjimelito** [comment]
Sure, I can definitely add one. I'll let you know when it's complete for
further review.

**Comment by BenGitsCode** [comment]
I was told we should create solution branches for everything, I'm curious about whether or not that should extend to studies as well but I'll open that as an instructors discussion.

**Pull request merged**
